# Generated by Django 6.0.3 on 2026-03-19 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climbing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='area',
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
